apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 3
    template:
        spec:
            containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                      - containerPort: 80
