apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana
spec:
    replicas: 1
    template:
        spec:
            containers:
                - name: grafana
                  image: grafana/grafana:latest
                  ports:
                      - containerPort: 3000
